/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.torreshanoi.fronted;

import com.mycompany.torreshanoi.objets.torre;
import java.util.Arrays;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author carlo
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    private torre tr = new torre();
    private int movimientos = 0;
    private String[] arregloFinal;
    private int movMax=0;
    private boolean bandera=true;
    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        centrar();
        activarMovimientos(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        torreC = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        torreA = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        torreB = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        unoAdos = new javax.swing.JButton();
        unoAtres = new javax.swing.JButton();
        dosAuno = new javax.swing.JButton();
        dosAtres = new javax.swing.JButton();
        tresAuno = new javax.swing.JButton();
        tresAdos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cantidadComboBox = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        movimientosjTextField = new javax.swing.JTextField();
        maximajTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(255, 0, 0)));

        jScrollPane1.setViewportView(torreC);

        jScrollPane2.setViewportView(torreA);

        jScrollPane3.setViewportView(torreB);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("TORRE 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("TORRE 2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("TORRE 3");

        unoAdos.setText("2");
        unoAdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoAdosActionPerformed(evt);
            }
        });

        unoAtres.setText("3");
        unoAtres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoAtresActionPerformed(evt);
            }
        });

        dosAuno.setText("1");
        dosAuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosAunoActionPerformed(evt);
            }
        });

        dosAtres.setText("3");
        dosAtres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosAtresActionPerformed(evt);
            }
        });

        tresAuno.setText("1");
        tresAuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresAunoActionPerformed(evt);
            }
        });

        tresAdos.setText("2");
        tresAdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresAdosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(unoAdos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unoAtres)
                        .addGap(79, 79, 79)
                        .addComponent(dosAuno)
                        .addGap(18, 18, 18)
                        .addComponent(dosAtres)
                        .addGap(70, 70, 70)
                        .addComponent(tresAuno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tresAdos)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(116, 116, 116)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unoAdos)
                    .addComponent(unoAtres)
                    .addComponent(dosAuno)
                    .addComponent(dosAtres)
                    .addComponent(tresAuno)
                    .addComponent(tresAdos))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TORRES DE HANOI");

        jPanel4.setBackground(new java.awt.Color(0, 255, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 0, 0)));

        cantidadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jButton7.setText("Jugar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        movimientosjTextField.setEditable(false);

        maximajTextField.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel9.setText("ALTURA DE LA TORRE");

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel10.setText("CANTIDAD MÍNIMA DE MOVIMIENTOS");

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel11.setText("MOVIMIENTOS REALIZADOS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(maximajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(movimientosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maximajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movimientosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel4)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String cantidad = this.cantidadComboBox.getSelectedItem().toString();
        iniciar(cantidad);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void unoAdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoAdosActionPerformed
        // TODO add your handling code here:
        if (tr.movimiento(torreA, torreB)) {
            movimientos++;
            this.movimientosjTextField.setText(String.valueOf(movimientos));
            this.verificarGanador();
        }
    }//GEN-LAST:event_unoAdosActionPerformed

    private void unoAtresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoAtresActionPerformed
        // TODO add your handling code here:
        if (tr.movimiento(torreA, torreC)) {
            movimientos++;
            this.movimientosjTextField.setText(String.valueOf(movimientos));
            this.verificarGanador();
        }
    }//GEN-LAST:event_unoAtresActionPerformed

    private void dosAunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosAunoActionPerformed
        // TODO add your handling code here:
        if(tr.movimiento(torreB, torreA)){
            movimientos++;
            this.movimientosjTextField.setText(String.valueOf(movimientos));
            this.verificarGanador();
        }
    }//GEN-LAST:event_dosAunoActionPerformed

    private void dosAtresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosAtresActionPerformed
        // TODO add your handling code here:
        if(tr.movimiento(torreB, torreC)){
            movimientos++;
            this.movimientosjTextField.setText(String.valueOf(movimientos));
            this.verificarGanador();
        }
    }//GEN-LAST:event_dosAtresActionPerformed

    private void tresAunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresAunoActionPerformed
        // TODO add your handling code here:
        if(tr.movimiento(torreC, torreA)){
            movimientos++;
            this.movimientosjTextField.setText(String.valueOf(movimientos));
            this.verificarGanador();
        }
    }//GEN-LAST:event_tresAunoActionPerformed

    private void tresAdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresAdosActionPerformed
        // TODO add your handling code here:
        if(tr.movimiento(torreC, torreB)){
            movimientos++;
            this.movimientosjTextField.setText(String.valueOf(movimientos));
            this.verificarGanador();
        }
    }//GEN-LAST:event_tresAdosActionPerformed

    private void iniciar(String cantidad) {
        String[] init = {" ", " ", " ", " ", " "};
        torreB.setListData(init);
        torreC.setListData(init);
        torreA.setListData(tr.torreAsignada(cantidad));
        this.movimientosjTextField.setText(String.valueOf(movimientos));
        this.movMax=tr.calculoMovimientos(Integer.valueOf(cantidad));
        this.maximajTextField.setText(String.valueOf(movMax));
        this.arregloFinal = tr.obtener(torreA);
        activarMovimientos(true);
        bandera=true;
        movimientos=0;
        this.movimientosjTextField.setText(String.valueOf(movimientos));
    }

    private void activarMovimientos(boolean estado) {
        this.unoAdos.setEnabled(estado);
        this.unoAtres.setEnabled(estado);
        this.dosAuno.setEnabled(estado);
        this.dosAtres.setEnabled(estado);
        this.tresAuno.setEnabled(estado);
        this.tresAdos.setEnabled(estado);
    }

    public void centrar() {
        DefaultListCellRenderer cellRenderer = (DefaultListCellRenderer) torreA.getCellRenderer();
        cellRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultListCellRenderer cellRenderer2 = (DefaultListCellRenderer) torreB.getCellRenderer();
        cellRenderer2.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultListCellRenderer cellRenderer3 = (DefaultListCellRenderer) torreC.getCellRenderer();
        cellRenderer3.setHorizontalAlignment(SwingConstants.CENTER);
    }
    public void verificarGanador(){
        String cantidad = this.cantidadComboBox.getSelectedItem().toString();
        System.out.println("Maximo: "+movMax+" Movimiento: "+movimientos);
        System.out.println("Arreglo final: "+arregloFinal.toString()+" Arreglo de C: "+tr.obtener(torreC).toString());
        //if(movMax==movimientos && arregloFinal.equals(tr.obtener(torreC))){
        if(movMax==movimientos && Arrays.equals(arregloFinal,tr.obtener(torreC))){
            JOptionPane.showMessageDialog(this, "Logro resolver el juego FELICITACIONES!!!!", "Logrado", JOptionPane.INFORMATION_MESSAGE);
            iniciar(cantidad);
        }
        if(movimientos>movMax){
            if(this.bandera){
                JOptionPane.showMessageDialog(this, "Supero el minimo de movimientos para completarlo", "Supero el minimo", JOptionPane.WARNING_MESSAGE);
                bandera=false;
            }
            
            if(Arrays.equals(arregloFinal,tr.obtener(torreC))){
                JOptionPane.showMessageDialog(this, "Logro resolver el juego, superando el minimo", "Supero el minimo", JOptionPane.WARNING_MESSAGE);
                iniciar(cantidad);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cantidadComboBox;
    private javax.swing.JButton dosAtres;
    private javax.swing.JButton dosAuno;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField maximajTextField;
    private javax.swing.JTextField movimientosjTextField;
    private javax.swing.JList<String> torreA;
    private javax.swing.JList<String> torreB;
    private javax.swing.JList<String> torreC;
    private javax.swing.JButton tresAdos;
    private javax.swing.JButton tresAuno;
    private javax.swing.JButton unoAdos;
    private javax.swing.JButton unoAtres;
    // End of variables declaration//GEN-END:variables
}
